name: CI/CD

on: [pull_request, push]

jobs:
  check:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
      - run: |
          cargo install grcov && cargo install cargo-sort
          yarn && yarn workspace @white-rabbit/app-desktop run build:vue
          yarn lint && yarn test:coverage
        name: Test and coverage
      - uses: codecov/codecov-action@v4
        if: matrix.platform == 'ubuntu-latest'
        with:
          files: target/debug/coverage/lcov.info
          flags: unittests,backend
        name: Push coverage to Codecov
      - name: Push coverage to Codacy
        if: matrix.platform == 'ubuntu-latest'
        uses: codacy/codacy-coverage-reporter-action@v1
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: target/debug/coverage/lcov.info
      - name: SonarCloud Scan
        if: matrix.platform == 'ubuntu-latest'
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - run: yarn build
        name: Build release